### ISSUE TITLE
Forum page: 'Show bibtex' doesn't work

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-web#148]
The link is not clickable, please check this example in the dev site:

https://dev.openreview.net/forum?id=7xtTUJGz3

**Comment by JeffFessler** [comment]
The "BibTeX" link under the author list is (again?) not working.
(Tried both Chrome and Safari on MacOS.)
Here is an example page: https://openreview.net/forum?id=v7ZPwoHU1j
And the `BibTeX` link is this url: https://openreview.net/forum?id=v7ZPwoHU1j#
The `Revisions` link works fine https://openreview.net/revisions?id=v7ZPwoHU1j
and that revisions link looks like a sensible link, whereas the bibtex link seems dubious - just one extra `#`?

I tried the natural (?) url `https://openreview.net/bibtex?id=v7ZPwoHU1j` but no luck.
