### ISSUE TITLE
User moderation - moderation queue may show empty results

### ISSUE THREAD

**Issue by xkopenreview** [openreview/openreview-web#1654]
the moderation queue has a default page size 15.
for example there are 16 profiles pending moderation and the moderator go to page 2 and approved the 16th profile.

the moderation queue currently shows no profiles pending
<img width="903" alt="image" src="https://github.com/openreview/openreview-web/assets/60613434/2860a2c9-f3f0-4f6d-81f3-b001c7a060e6">

i think it should set the page number to 1

**Comment by pmandler-umass** [comment]
Go to /user/moderation as SUPER_USER to see profile moderation.
