### ISSUE TITLE
Invitation editor: saving a date process function doesn't work

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-web#1799]
When trying to edit the cron string for the TMLR invitation, I get the following error: "Error: startDate must be string,integer"

How to reproduce it: https://openreview.net/invitation/edit?id=TMLR/Reviewers/-/Assignment_Availability

Try editing something and click on "Save Data Processes".

**Comment by xkopenreview** [comment]
i think the startDate and endDate are not allowed to be null
what's the expected behavior?

**Comment by melisabok** [comment]
it is that from Python is allowed: https://github.com/openreview/openreview-py/blob/master/openreview/journal/invitation.py#L1710

**Comment by xkopenreview** [comment]
> it is that from Python is allowed: https://github.com/openreview/openreview-py/blob/master/openreview/journal/invitation.py#L1710

if you don't pass startDate and endDate it will not trigger validation
if ui do the same it will cause startDate/endDate to be not removable once added

@carlosmondra i think null should be allowed in dateprocess.cron.startDate/endDate to allow removal

**Comment by carlosmondra** [comment]
`null` values are not allowed because we don't have a way to validate them using an invitation.

**Comment by xkopenreview** [comment]
currently the date process editor always pass a string when startDate and endDate have value
one possible solution and to convert it to number when it's number and user should put 0 to remove the value
so that when api check processInfo.startDate/endDate it will evaluate to false

**Comment by carlosmondra** [comment]
Why don't we use `{ delete: true }` for this? I can enable that.

**Comment by xkopenreview** [comment]
> Why don't we use `{ delete: true }` for this? I can enable that. Otherwise, it feels very hacky.

sure #1802
