### ISSUE TITLE
Group editor: load all related invitations

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-web#1837]
When loading all the invitations related to the group, use the following prefix:

```
thecvf.com/CVPR/2024/Conference/Submission4/.*
```

instead of

```
thecvf.com/CVPR/2024/Conference/Submission4/-/.*
```

so invitations like thecvf.com/CVPR/2024/Conference/Submission4/Meta_Review1/-/Final_Revision can be found.

**Comment by xkopenreview** [comment]
this should be only applied to groups that contains submission name
otherwise all invitations will be loaded for venue group

**Comment by melisabok** [comment]
Good point, how do we distinguish them?

**Comment by xkopenreview** [comment]
> thecvf.com/CVPR/2024/Conference/Submission4/Meta_Review1/-/Final_Revision

i'm checking the group id includes submission name
