### ISSUE TITLE
Messages UI: message log is pointing to API 1. 

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-web#1838]
It should point to API 2, new messages with invitations are going to be accesible by API 2 only.

**Comment by xkopenreview** [comment]
currently all messages are posted to v1 in openreview-web,
are the message with invitations posted from openreview-py?

notifications page also get all messages so i think it's not just the message log link

**Comment by carlosmondra** [comment]
Melisa and I discussed this again. Messages will still be accessible in both APIs, but openreview-web should be using the API 2 for messages.
