### ISSUE TITLE
Bidding Console: remove the call to `domain` when searching several notes by id

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-web#1841]
The API is not going to allow this parameter in the future: https://github.com/openreview/openreview-api/pull/375

**Comment by xkopenreview** [comment]
from the chat messages it looks like domain should still be added
so is this issue still valid?

**Comment by melisabok** [comment]
I do think the API is planning to remove it soon. cc @carlosmondra 

This is only for searching notes by ids, is the chat messages using this call?

**Comment by xkopenreview** [comment]
> I do think the API is planning to remove it soon. cc @carlosmondra
> 
> This is only for searching notes by ids, is the chat messages using this call?

sorry i mean the slack chat messages between you and Carlos, not the forum chat
