### ISSUE TITLE
Profile edit validation: mark required fields correctly

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-web#1860]
1. When one home page url is missing, only the Homepage URL is marked in red. I suggest to mark all of them so users don't think they need to enter a homepage url only:

<img width="870" alt="Screen Shot 2024-03-18 at 10 45 41 AM" src="https://github.com/openreview/openreview-web/assets/545506/ef4253c1-8588-4815-ab5c-0b596f12784d">

2. When education and history is empty, there is not red indicator in the first record.

<img width="1133" alt="Screen Shot 2024-03-18 at 10 47 00 AM" src="https://github.com/openreview/openreview-web/assets/545506/c0e8f9e4-ae4f-46b8-90f0-80d84015f5b3">

To make the validation more clear, can we show the validation messages next to each field names like we are doing with note editor now? cc @zbialecki

**Comment by zbialecki** [comment]
I think that's OK.
