### ISSUE TITLE
Consoles/Tabs - default to first tab when location hash is invalid

### ISSUE THREAD

**Issue by xkopenreview** [openreview/openreview-web#1877]
currently the consoles show blank when the location hash does not match any tab id or the specified tab is hidden

i think it should show switch to the first tab instead of showing blank

**Comment by pmandler-umass** [comment]
Please describe how to create this situation.
Login as a PC, go to the PC console ....

**Comment by pmandler-umass** [comment]
It appears this situation may occur when someone saves the link to a tab that no longer exists.
