### ISSUE TITLE
Allow functions for search query

### ISSUE THREAD

**Issue by haroldrubio** [openreview/openreview-web#1925]
The webfield config field `propertiesAllowed` only allows querying by a field in the `rowData` but it does not support functions over the row data, like when we need to compute something over a subset of the replies

**Comment by melisabok** [comment]
Let's discuss how to implement this here. 

propertiesAllowed should be able to receive either a string or JS function that iterates through rowData to check the replies?

**Comment by melisabok** [comment]
so the query language would be `+hasMetaReview = true`

is there possible to support value that are not boolean, for example `+commentCount > 3`
