### ISSUE TITLE
DatePicker widget - support maximum and minimum

### ISSUE THREAD

**Issue by xkopenreview** [openreview/openreview-web#2047]
Based on https://github.com/openreview/openreview-api/pull/488/files#diff-646b69aba0c89ba4c90e0499a87b70a09b10f61535e240d0e7053405060331b7R877
it's possible to the param of type date/date[] (which is rendered as date picker widget) to include minimum/maximum

this is currently not supported in the widget

rc-picker has a disabledDate property which might be used to disable dates outside minimum and maximum

**Comment by melisabok** [comment]
I don't think this is a high priority now, I don't have any case when I want to limit the value of the date.
