### ISSUE TITLE
PC/SAC console: Don't show AC name if there are no assigned ACs

### ISSUE THREAD

**Issue by enrubio** [openreview/openreview-web#2056]
Don't show AC name if there are no assigned ACs. PC console ex:

<img width="500" alt="Screenshot 2024-08-08 at 5 56 26 PM" src="https://github.com/user-attachments/assets/fc702367-fb61-4e11-b0f1-f9fb9641c9de">

I think this is fixed here:
https://github.com/openreview/openreview-web/blob/cd2b4b41318828227cc8cf504b7b4b155e4ed7b5/components/webfield/NoteMetaReviewStatus.js#L220-L222

**Comment by pmandler-umass** [comment]
@enrubio your example shows Senior Program Committee not ACs.  Would the "Hide Program Committee" also be removed?  I'm having trouble finding this part of the console - what tab is it under?
